name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "jiankon"
database_id = "177cf780-517c-4c5f-a1ec-1353fa8284a8"

[version_metadata]
binding = "CF_VERSION_METADATA"
